apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: capz-aster-platform-chart
  namespace: capz-aster
spec:
  interval: 30m
  provider: generic
  url: oci://ghcr.io/willie-yao/charts/aster-platform
  ref:
    tag: "0.9.0-rc.8"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
